### ISSUE TITLE
warning Creating a duplicate database object for the same connection.

### ISSUE THREAD

**Issue by mapsgeek** [tobinbradley/dirt-simple-postgis-http-api#11]
i hit this warning in the console once a request is made for a mvt, 
`warning Creating a duplicate database object for the same connection`
the tiles are getting delivered in one response not twice but once you set up an onclick event that returns feature properties, it returns 2 objects in the array for the same layer, so any clue on that ?
also i have a question, i noticed that you didn't put the .pbf extension on the tiles path and it works fine returning the tiles but just a thought why not adding it ?

**Comment by tobinbradley** [comment]
There's too much going on there for me to hazard a guess. Could be the data, the JS client, the client side code, the server, or some combination of those.

As to why no pbf extension, it isn't necessary, and if you send a request for an area with no data, you won't get a pbf back, you'll get a 404 (that's how MapBox handles no data tiles, so I did the same).

**Comment by mapsgeek** [comment]
well after a bit of debugging, the issue related to the (pg-promise ), what is causing this warning is that you set the connection for the database each time a request made made for a service by putting the declaring the db variable inside the handler function like that

`    handler: function(request, reply) {
        let db = pgp(config.db.postgis);
        db
            .query(formatSQL(request))
            .then(function(data) {
                reply(data);
            })
            .catch(function(err) {
                reply({
                    'error': 'error running query',
                    'error_details': err
                });
            });
    }`
based on the question here [https://github.com/vitaly-t/pg-promise/issues/299](url)
so taking the `let db = pgp(config.db.postgis);` outside the handler fun solve this and avoid re-creating of the database connection with every tile requested, i don't know how would this effect performance or not but here it's anyway.

**Comment by tobinbradley** [comment]
Awesome, thanks! From your original comment I thought you saw that message in the browser console. I'll check it out.

**Comment by mapsgeek** [comment]
oh sorry for confusion, just to inform you that this warning has nothing to do with the double return for the properties object i mentioned earlier " that was my fault ", and also as i said i'm not sure if it cause any performance issues but at least you won't have a server logs full of this message, i just deployed to heroku and tested in maputink, everything works like a charm.

**Comment by tobinbradley** [comment]
No worries, thanks for researching the warning message!

**Comment by vitaly-t** [comment]
The warning came from [pg-promise](https://github.com/vitaly-t/pg-promise), and the explanation can be found here: http://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise

**Comment by slidenerd** [comment]
> you should share the database object, as shown above, not re-create it all over again.

I have a file with [your Robust Listener](https://github.com/vitaly-t/pg-promise/wiki/Robust-Listeners) code in it
I also have another file with [your db initialization code](https://github.com/vitaly-t/pg-promise-demo/blob/master/JavaScript/db/index.js) in it 
Should both be the way they are or should I share, its a permanent listener

**Comment by vitaly-t** [comment]
@slidenerd [it was asked again recently](https://stackoverflow.com/questions/45427280/postgres-listen-notify-with-pg-promise/45427354?noredirect=1#comment110627723_45427354).
