### ISSUE TITLE
restrict the fetching query with a bounding box

### ISSUE THREAD

**Issue by mapsgeek** [tobinbradley/dirt-simple-postgis-http-api#12]
i was wondering and trying to understand what's going on here and if it's the normal thing that the server tries to fetch tiles in areas outside of the data extent, so it ends up with more requests and also more error logs! which i kinda don't like it.

![capture](https://user-images.githubusercontent.com/10188264/29605266-84a5da9a-87ea-11e7-809b-c46976216125.JPG)

so i don't know if my thought is right but can attaching a bounding box to the query along with the table name would solve this ?
if what i'm saying makes sense so please guide me where i can edit to fix this.
thnx

**Comment by tobinbradley** [comment]
The place to fix that is in the style JSON file. There's an [optional `bounds` parameter](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-vector-bounds) for vector and raster sources that limits the tile requests to that extent. Without that set the client assumes you've got the whole planet, hence the 404's when you go beyond the extent of your data.

Unfortunately I think the `bounds` parameter is fairly new and I don't see it as an option on the source modal in maputnik. You'd have to add that to the JSON file by hand. 

The 404 thing isn't harmful per se, but it certainly is annoying, and it's wasted HTTP requests.
