### ISSUE TITLE
Geocode Feature

### ISSUE THREAD

**Issue by mgottholsen** [tobinbradley/dirt-simple-postgis-http-api#15]
Do you have plans to implement geocode, or reverse geocode functionality with this? What would the barrier be to say, use a list of address with coordinates (lat,long or state plane etc), and perform geocoding functions from that?

**Comment by tobinbradley** [comment]
I don't have any plans. Geocoding is highly data-specific - there's no great way to generalize that into a service that I can think of. Besides the various way people store addresses as text, handle abbreviations, etc., geocoding can also involve interpolation of position along lines (i.e. geocoding to roads), or points/polys for more exact address locations. 

So...yuck :). If you can think of a way to elegantly handle all the possible permutations I'm all ears.

For reverse geocoding, I'd use the nearest service to yank the address from point features.
