### ISSUE TITLE
REST API security and Authentication

### ISSUE THREAD

**Issue by mapsgeek** [tobinbradley/dirt-simple-postgis-http-api#16]
Hi tobin, i noticed your updates today to the server and i'm about to use it in a project but i'm concerned about how to implement authentication on a certain or all the end points.
since the api is written in hapi framework so i'm looking for resources about that if you have good ones.
also if you have a plan to implement this in the future ?

**Comment by tobinbradley** [comment]
I haven't done that before, but that's a wheel we don't have to invent - the [Hapi plugins page](https://hapijs.com/plugins) has 20+ different plugins for authorization and authentication. The [Bell](https://github.com/hapijs/bell) plugin seems to be popular if you're looking for 3rd party authentication (Facebook/Google/etc.).
