### ISSUE TITLE
Problems setting up a new search

### ISSUE THREAD

**Issue by mtravis** [tobinbradley/dirt-simple-postgis-http-api#2]
Hi Tobin

Firstly, thanks for another great project! It's going to be really useful.

I've set up an API running from here: http://maps.moorthanmeetstheeye.org/api/documentation

It seems to be working fine apart from the search. 

I've edited config/index.js to include this search: 

```
mons: {
      table: 'monument_point',
      columns: `name`,
      where: `name ilike ?`,
      format: function(query) { return '%' + query.trim() + '%'; } 
    }
```

When I try use the search tool on the docs page I get this error.  

![dirt-simple-api-error](https://cloud.githubusercontent.com/assets/1799238/14737607/d12a14a4-0874-11e6-9581-b99363db722d.png)

I've tried changing the table to monument_point (the actual table as its know in the database) but that just gives me a 500 error? Where am I going wrong?

Cheers

Matt

**Comment by tobinbradley** [comment]
If you look at the top of index.js in config, the comments will show the required return columns for the search in my usual unhelpful/vague way: 

``` javascript
// Each search must return the fields id, label, type, lng, lat, pid, and address.
```

But that isn't exactly right. Search does a union of all the search tables in the request, so for the most part the fields returned in each search only have to match each other, and they really only have to match each other for multiple tables searched in one query. 

Except...the way it's set up you do need to return the columns `type` and `label`, because it does an `order` SQL clause with those. With the one return column you have specified now the SQL it creates looks like this:

``` sql
(SELECT name FROM monument_point WHERE (name ilike '%test%') LIMIT 10) order by type, label
```

Since there aren't type or label columns in your query, it's dying on the last bit. If you change your config to something like:

``` javascript
mons: {
      table: 'monument_point',
      columns: `name as label, 'monuments' as type`,
      where: `name ilike ?`,
      format: function(query) { return '%' + query.trim() + '%'; } 
    }
```

That should work. I think.

Sorry - I'll tighten up the documentation in index.js.

**Comment by mtravis** [comment]
Thanks for getting back so quickly. I somehow missed the glaringly obvious comments at the top there :)

I tried changing the config to what you suggested but that didn't work so I've tried to be more explicit and use this:

```
mons: {
      table: 'monument_point',
      columns: `ogc_fid as pid, monuid as label, montype as type, round(ST_X(ST_Transform(wkb_geometry, 4326))::NUMERIC,4) as lng, round(ST_Y(ST_Transform(wkb_geometry,4326))::NUMERIC,4) as lat, name as address`,
      where: `name ilike ?`,
      format: function(query) { return '%' + query.trim() + '%'; } 
    }
```
Should that work. It doesn't at present?

**Comment by tobinbradley** [comment]
Hmm...

Does your client login have select access to the table? Are you sure you're not looking at a cached result?

I just made a table called monuments_point -

``` sql
CREATE TABLE monuments_point
(
  code character(5) NOT NULL,
  name character varying(40) NOT NULL,
  CONSTRAINT firstkey PRIMARY KEY (code)
)
WITH (
  OIDS=FALSE
);
```

- threw a single record in it with a name value of 'test', set up the config this way -

``` javascript
mons: {
      table: 'monuments_point',
      columns: `name as label, 'monuments' as type`,
      where: `name ilike ?`,
      format: function(query) { return '%' + query.trim() + '%'; }
    }
```

- and darn if it didn't work -

![Imgur](http://i.imgur.com/AZMda1g.png)

By default the results are caching in the browser, so try changing the limit value to make it run a new query or launch it in private browsing mode.

**Comment by mtravis** [comment]
​I've just realises that I'm running this through a proxy the main site is
apache and I've added a proxypass to the conf file for the site.

Would this affect it?

Cheers

Matt​

**Comment by tobinbradley** [comment]
Nope. Mecklenburg does the same thing. You can have other Apache rules changing incoming requests in any number of breaking ways, but that would most likely manifest itself as a 404.

You could stick a console.log(sql) in the fetch to see what SQL call is being sent and try to run it straight at your DB to see what happens.

**Comment by mtravis** [comment]
Ok great. I'll give that a go and let you know how I get on.

**Comment by mtravis** [comment]
I think I've made a bit of a school boy error here. After adding  console.log(sql) to the fetch function I realised that at no point I had tried restarting the node app. 

I was using forever (good or bad idea? ) and thought that I could make changes to config without restarting. Maybe I'm getting confused with gulp. 

Anyhow, got it working now so all's good in the hood. 

Thanks and massive props for the awesome app!

**Comment by tobinbradley** [comment]
No worries! Glad it got sorted. 

forever is good. forever has a watch option that restarts the server on file change. You can use it like:

``` terminal
forever --watch --watchDirectory ./path/to/dir ./start/file
```

The hip thing right now seems to be using forever in conjunction with nodemon instead, but I don't know why. Something like:

``` terminal 
forever -c nodemon --exitcrash app.js
```

**Comment by mtravis** [comment]
Cool. I'll give the watch option a go. 

I'll leave the nodemon combo to the hipsters!
