### ISSUE TITLE
Data is offsetting in low zoom levels

### ISSUE THREAD

**Issue by mapsgeek** [tobinbradley/dirt-simple-postgis-http-api#20]
i wanted to give the mvt endpoint a shot after the last query optimization video, the performance is great i barley notice any CPU usage ! but there's a problem in rendering data at zoom levels before 7
tried with multiple data sources imported using db manager in qgis, targeted SRID 4326.
data is rendered offset-ed and distorted at zoom level 0,1,2 with each zoom level you hit the offset goes back to right place until zoom level 7
can you please see if you can replicate this ?

*** system running postgresql 10.6 and postgis 2.5

![image](https://user-images.githubusercontent.com/10188264/48503732-97192980-e84b-11e8-9384-c86710acd31d.png)
![image](https://user-images.githubusercontent.com/10188264/48503747-a4ceaf00-e84b-11e8-88ba-a870504799a6.png)

**Comment by tobinbradley** [comment]
Letting me know about these things is an invaluable service. As I work with a local municipality, I never tested on the scales you are, so I never saw this bug.

I *think* I have it fixed, though with a caveat. I found a [post](https://gis.stackexchange.com/questions/299085/postgis-st-asmvt-latitude-incorrect-at-low-zoom-levels) where somebody had the same problem. It appears to be an issue with converting to 4326 instead of 3857. Now there's no jumping about.

It can, however, create another problem. 3857 doesn't like features with latitude 0 [see this issue](https://trac.osgeo.org/postgis/ticket/1690), as in 3857 0 latitude seems to be like infinity places or something. I noticed my Natural Earth countries would error on the tiles that would hit the bottom of the map as I had them stored in 4326. I projected them to 3857 in QGIS, and immediately noticed the bottom of the map was shortened. Loading that into PostGIS and drawing from there seemed to do the trick.

So...better-ish.

**Comment by tobinbradley** [comment]
I confirmed what the other problem was.

![https://i.imgur.com/vpY8z02.png](https://i.imgur.com/vpY8z02.png)

If you try to create a tile with features that sit outside of the extent of web mercator (-180.0 -85.06 180.0 85.06 - [see projection info](https://epsg.io/3857)), the tile won't render. This makes sense - it's trying to do a ST_Transform to EPSG:3857, and the coordinates you are passing don't exist in EPSG:3857. You'll get an error message to that effect.

You may not run in to that issue at all. If you do, you have two options: you can project the data to 3857, which should take care of things, or you can clip the data to the boundaries of 3857, ala something like:

```sql
update countries
set geom = st_multi(
	st_intersection(
		geom, 
		ST_MakeEnvelope(-180.0, -85.06, 180.0, 85.06, 4326)
	)
)
```

Note either of those are destructive changes, so don't try it on data you don't have backups of. I ran the SQL on Natural Earth countries, and it fixed the issue of tiles that touch the south pole not rendering.

Thanks for letting me know about the problem!

**Comment by mapsgeek** [comment]
thank you it worked just fine, i remember that before submitting that issue that i tried changing the SRID on the shapefile level and also in the query code to 3857 and ended up having the data falling into the Null island !
thought i was looking into a wrong direction and gave up.
however i can hear you on the 3857 problems here's a note as well on performance on right now

- If your data is in 4326 and the query do transform to 3857, data renders fine but performance is bad like before, very high CPU usage with 500ms ~ 1.5 second response time on localhost ( tested in chrome ) with multi-string geom and multipolygon, depends on the geometry complexity, fine with points !

which i thought that the query optimization has fixed, upload data in 3857 to avoid transformation and you get 204 error which in the code for no tiles !

try this [shapefile](https://www.census.gov/geo/maps-data/data/cbf/cbf_ua.html)

**Comment by mapsgeek** [comment]
i can confirm that you will run into rendering issues with 3857 and that clip is necessary to fixes all rendering issues but now performance hits are back

If your data is in 4326 and the query do transform to 3857, clip has executed as you suggested data renders fine but performance is bad like before, very high CPU usage with 500ms ~ 1.5 second response time on localhost ( tested in chrome ) with multi-string geom and multipolygon, depends on the geometry complexity, fine with points and natural earth 110m try with countries 10m and you will see the hit !
which i thought that the query optimization has fixed, and wasn't there actually before your last commit to fix the jumping issue.

**Comment by tobinbradley** [comment]
I don't think that's a projection issue - seems the same with that shape file in it's native 4269 or projected to 3857. That's just a lot of fairly complex data to try and draw at that scale on the fly. It goes  fast zoom > 9 - tiles render in <200ms (that's projecting to 3857 on the fly). As you support lower zoom levels, the tiles get much bigger, and it naturally slows down. More data in a tile will directly translate in to more time making the tile. The SQL query still shows as using the spatial index. 

If you really want to draw that at very low zoom levels, you could try to simplify it (greatly) beforehand. This seemed to speed it up a lot, and I couldn't tell much of a difference at that scale:

```sql
  update census_urban_3857
  set geom = ST_Multi(ST_SimplifyPreserveTopology(geom, 10000))
```

At zoom 4 this has the slowest tile coming in ~700ms for me. 

But for something that changes so infrequently, I'd stick with tippecanoe. No sense thrashing your database if you don't need to. I'd reserve direct database feature calls for things that change often enough to make tippecanoe a pain, and then tune that data for performance accordingly.

**Comment by mapsgeek** [comment]
yeah that's what it's all about our data changes frequently and it's global data so low zoom levels are crucial and i wanted to get ride of the Tippecanoe process but seems like i will have to stick with it then, thank you
