### ISSUE TITLE
SwaggerUIBundle is not defined

### ISSUE THREAD

**Issue by mtravis** [tobinbradley/dirt-simple-postgis-http-api#24]
I've just upgraded to the newer version and hit a snag. 

Getting a empty screen and this error in my console: 

`api:40 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (api:40)`

See for yourself: http://all-mapped-out.co.uk/api

I'm running a proxy on my apache server using these parameters (from an older version):

`        ProxyPass /api http://localhost:3000 `
`        ProxyPass /swaggerui http://localhost:3000/swaggerui`

And these options in my config: 
```
"swagger": {
    "basePath": "/api",
    "externalDocs": {
      "url": "https://github.com/tobinbradley/dirt-simple-postgis-http-api",
      "description": "Source code on Github"
    }
```

Might be really something simple I'm missing but I'm totally stumped!

**Comment by tobinbradley** [comment]
Best guess is you're running into the same trailing slash issue you had with nginx. Apache treats trailing slashes in much the same way as nginx, though I think with apache both arguments require a trailing slash.

**Comment by mtravis** [comment]
Wow, who knew! So it's just a case of explicitly using  http://all-mapped-out.co.uk/api/

**Comment by tobinbradley** [comment]
Glad it works! 

Swagger docs are static in the documentation folder now (swagger config still auto-generated), and are treated like a regular route (documentation.js in the routes folder). That eliminates proxy issues and lets you customize your doc page however you want.

**Comment by Basavarajrp** [comment]
> Best guess is you're running into the same trailing slash issue you had with nginx. Apache treats trailing slashes in much the same way as nginx, though I think with apache both arguments require a trailing slash.
> 
> Also, you shouldn't need a separate proxy for swaggerui anymore.

Heeyy Thank you this helped my problem.
