### ISSUE TITLE
geobuf error when empty result

### ISSUE THREAD

**Issue by NessterGit** [tobinbradley/dirt-simple-postgis-http-api#25]
Hi, thanks for the great tool ! 

Just a heads up: when using the geobuf route, if the query returns an empty result, there's a server error in (if using pm2) ~/.pm2/logs/index-error.log:

> TypeError: Cannot read property 'length' of null
    at Query.onResult ([...]/dirt/routes/geobuf.js:118:24)

**Comment by tobinbradley** [comment]
Thanks for letting me know about the problem! Should be fixed now.

**Comment by NessterGit** [comment]
> Thanks for letting me know about the problem! Should be fixed now.

Yes it is! Thank you
