### ISSUE TITLE
Why not use node-mapnik ?

### ISSUE THREAD

**Issue by clouddie** [tobinbradley/dirt-simple-postgis-http-api#3]
Hi, just read you [post on GEOJSON there] (http://fuzzytolerance.info/blog/2016/07/31/Adding-GeoJSON-and-MVT-to-PostGIS-HTTP-API/)

It seems that node-mapnik allows you to directly query a postgis datasource and transform it directly into vector tiles (see the [docs](http://mapnik.org/documentation/node-mapnik/3.5/#Map.render)). Why do you then go through the hassle of first converting your query results to GeoJson, and then to a vector tile ?

I am asking the question because I never managed to do it properly from a postgis datasource with node-mapnik, just from a shape datasource (and it works well). I was wondering what were your views on this.

**Comment by tobinbradley** [comment]
You could use either. Based on [Frank Rowe's example](http://frankrowe.org/posts/2015/03/17/postgis-to-protobuf.html), the first time I tried using mapnik to render the vector tiles on a test project. Then I tried [vt-pbf](https://github.com/anandthakker/vt-pbf) and [geojson-vt](https://github.com/mapbox/geojson-vt). Based on my testing the latter is faster, but they were so close as to be equivalent. 

So it was really a matter of personal preference. geojson-vt/vt-pbf is a much lighter project dependency than mapnik and the code felt cleaner. 

I never tried PostGIS as a layer source for mapnik, so I don't know about that. [Maybe this code would work](http://gis.stackexchange.com/questions/201573/node-mapnik-postgresql-vector-tiles-question). The wkb to geojson operation is surprisingly negligible in terms of performance, and I *imagine* Mapnik is doing something like it internally from the PostGIS WKB output. Most libraries like Mapnik translate various data input types into a common format for processing so the internal code isn't a big mess.

**Comment by clouddie** [comment]
@tobinbradley Hi, thanks for your answer. Your project did help me a lot by the way, I finally managed to query a post-gis datasource using your method. Many thanks,
