### ISSUE TITLE
Issue with non-default geometry column in MVT route

### ISSUE THREAD

**Issue by StefanBrand** [tobinbradley/dirt-simple-postgis-http-api#37]
## Expected

I can overwrite the default geometry column `geom`

## Actual

I cannot use a different name for the geometry column than `geom` (`wkb_geometry`, the default ingestion by OGR, does not work).

## Steps to reproduce

1. Try to access the MVT route on a database with a geometry column named other than `geom` -> ERROR 500 `"column \"geom\" does not exist"`
2. Rename table to `geom`
```sql
parcels=> ALTER TABLE wallonia_2018 RENAME COLUMN wkb_geometry TO geom;
ALTER TABLE
```
3. Try to access the MVT route again -> Works

### Screenshot of Swagger with input `wkb_geometry`
![Screenshot of Swagger with input wkb_geometry](https://user-images.githubusercontent.com/8948865/101772630-e940dd80-3aeb-11eb-9a15-bb3cefed82a9.png)

### Screenshot of Swagger with input `geom` after renaming column

![Screenshot of Swagger with input geom after renaming column](https://user-images.githubusercontent.com/8948865/101772823-2d33e280-3aec-11eb-9464-806b480c0ec6.png)

**Comment by tobinbradley** [comment]
Thanks for providing such a detailed bug report! It made it easy to track down the problem. I had `geom` hard coded in one part of the SQL call.

Do a git pull or overwrite your `routes/mvt.js` with the updated one and you should be good to go. 

Thanks for letting me know about the problem!

**Comment by StefanBrand** [comment]
Cool, so you closed this super-quickly in https://github.com/tobinbradley/dirt-simple-postgis-http-api/commit/3ba01215c9fb461a778f220652e3428f25821c7c Thank you!
