### ISSUE TITLE
Special Characters in search query

### ISSUE THREAD

**Issue by mtravis** [tobinbradley/dirt-simple-postgis-http-api#4]
I've added the search below to index.js 

```

 planapps: {
      table: 'planapp_points',
      columns: `ogc_fid as id,
                      appcode as label,
                      apptype as type,
                      round(ST_X(ST_Transform(geom, 4326))::NUMERIC,4) as lng,
                      round(ST_Y(ST_Transform(geom, 4326))::NUMERIC,4) as lat,
                      round(ST_X(ST_Transform(geom, 27700))::NUMERIC,4) as easting,
                      round(ST_Y(ST_Transform(geom, 27700))::NUMERIC,4) as northing`,
      where: `appcode ilike ?`,
      format: function(query) { return '%' + query.trim() + '%'; }
}
```

The search uses appcodes which are formed like so: 0482/15. Every entry will have the / character. 
When test this on the docs page get the error below. Do I need to format the query somehow? 

![image](https://cloud.githubusercontent.com/assets/1799238/18409627/c5401042-7743-11e6-85a3-589cb2087ea6.png)

**Comment by tobinbradley** [comment]
By default, Apache doesn't allows URLs which contain encoded path separators like `%2F` to be used in the path info, returning a 404 for those requests (the request never gets to the node service). So this is Apache ruining your day. I think if you hit the service directly it would work fine.

The proper fix is telling Apache to stop doing that. Put this in the bottom of you httpd.conf file, restart Apache, and your request should start working.

```
AllowEncodedSlashes NoDecode 
```

Docs: [AllowEncodedSlashes](https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes) 

If modifying your Apache config requires sacrificing a goat to your IT department, the quick/dirty fix would be to have the requesting client replace that character before it's sent and fix it on the service end. So if you replace the `/` with something like `--` behind the scenes before the request is sent, in the search setup you can have the format function switch it back to a `/`.

```javascript
planapps: {
      ...
      format: function(query) { return '%' + query.trim().replace('--', '/') + '%'; }
}
```

**Comment by mtravis** [comment]
Thanks Tobin. Just need find myself a goat now.
