### ISSUE TITLE
serve uncompressed tiles

### ISSUE THREAD

**Issue by JulieGoldberg** [tobinbradley/dirt-simple-postgis-http-api#41]
Is it possible to serve uncompressed tiles? I think that's my problem (though I'm not sure).

Dirt has been awesome for serving tiles that are rendered in a browser on my computer. It works when I'm showing them in Mapbox GL and when I'm showing them in Leaflet using Leaflet.vectorGrid.

To print maps with legends and other formatting, I'm using puppeteer and chromium to pull up a hidden page with a map and print it to PDF. I can pull up the page in my regular browser just fine but not in the headless browser. For every tile, chromium produces an error `"Uncaught Error: Unimplemented type: 3", source: http://127.0.0.1:8000/static/lib/leaflet-vectorgrid-1.3.0/Leaflet.VectorGrid.bundled.js (767)`
This makes me think it's because the tiles are rendered compressed. https://github.com/mapbox/tippecanoe/issues/793 

Is there a way to send the tiles not compressed? Or do you have other ideas on why Chromium would have errors rendering Dirt vector tiles in Leaflet when it works just fine in Chrome?

**Comment by tobinbradley** [comment]
Well that's super weird. 

In `index.js`, I specify the mime types to compress so I can add protobuf to the list. (Looking at the fastify-compress docs, I went a little overboard there and just needed to add x-protobuf.) 

You can try serving uncompressed protobuf by changing this bit in `index.js` - 

```javascript index.js
// compression - add x-protobuf
fastify.register(
  require('fastify-compress'), {
    customTypes: /^text\/|\+json$|\+text$|\+xml|x-protobuf$/
  }
)
```

To this - 

```javascript index.js
// compression
fastify.register(
  require('fastify-compress')
)
```

Let me know if that does it. It would be super weird if that worked though.

**Comment by JulieGoldberg** [comment]
I wish what you'd send were helpful. It did show that Dirt tiles can be printed. I was able to serve your page and print it using puppeteer using my standard script for such things, which is only slightly more complex than yours. But when I tried to add any logging to puppeteer, the printing stopped working. I was most interested to see what requests were being made. It would show the requests to get the page and the library but not to get tiles, and indeed, no tiles were rendered.

**Comment by JulieGoldberg** [comment]
I wish what you'd send were helpful. It did show that Dirt tiles can be printed. I was able to serve your page and print it using puppeteer using my standard script for such things, which is only slightly more complex than yours. But when I tried to add any logging to puppeteer, the printing stopped working. I was most interested to see what requests were being made. It would show the requests to get the page and the library but not to get tiles, and indeed, no tiles were rendered.

**Comment by JulieGoldberg** [comment]
Turns out serving uncompressed tiles wasn't the issue. That was just the issue that the map library showed when Dirt couldn't connect to the database to serve the tiles and sent back empty tiles or an error (I'm not sure which). 

Adding the ability to run Dirt in a verbose mode, where you can see queries, errors, etc. would be an awesome addition that would have helped a ton with debugging.
