### ISSUE TITLE
How can I get ID of feature in GeJSON

### ISSUE THREAD

**Issue by barnoma-soz** [tobinbradley/dirt-simple-postgis-http-api#46]
Hello.

Could you please take a moment and give your answer on this question below.

Saving geoJSON: Specify and remember ID field [#40876](https://github.com/qgis/QGIS/issues/40876)

**Comment by tobinbradley** [comment]
It seems like there might be a way to do that using Postgres's JSONB data type. I'll look into it.

**Comment by tobinbradley** [comment]
I pushed an update to the geojson route so it has an optional id column. Give it a shot.

**Comment by barnoma-soz** [comment]
Thank you, it works fine
