### ISSUE TITLE
column named q breaks the "/v1/mvt/" route

### ISSUE THREAD

**Issue by joseperez-GIS** [tobinbradley/dirt-simple-postgis-http-api#50]
Hello Tobey! 

I guess the title says it all. Here is a screenshot of the request:

![image](https://user-images.githubusercontent.com/107511412/173955436-39b16b80-a328-46c5-afac-e36ba2c1fbd2.png)

I've tried encoding the URI but it has not worked. I did noticed that there is a variable named "q" on the the geobuf.js class (line 50) and mvt.js line 12 and 46, but even changing the variable name to something else does not seem to work. Any help you could provide would help me a lot since I've been stuck on this for days... 

Anyway to sanitize the column input? 

Thank you!

Currently running the "postgis2x" branch.
node version: v12.14.1
npm version: 6.13.4

Error message:
{
    "statusCode": 500,
    "code": "XX000",
    "error": "Internal Server Error",
    "message": "pgis_asmvt_transfn: parameter row cannot be other than a rowtype"
}

**Comment by joseperez-GIS** [comment]
**What is q's data type?** text (see screenshot) 

**What happens if you rename the return column, like make the columns 'a,b,c,d,q as y,x'? Trying to see if there's a reserved string problem on the input or output end of things.**  Indicates the column does not exist:
![image](https://user-images.githubusercontent.com/107511412/174085429-981a1d9c-5bf4-408f-80ea-e8bbb16b7131.png)

Could you grab the latest routes/mvt.js and give it a try? I noticed yours is missing the id_column option, so you're a few updates and bug fixes behind the current version.  Here is the test with new version. However, the DB is running running Postgis 2.x, so maybe that could be causing the issue.
 
![image](https://user-images.githubusercontent.com/107511412/174087867-fb650b15-1a0c-4c76-877c-3dd63563682b.png)

Screenshots for reference:
![image](https://user-images.githubusercontent.com/107511412/174084972-c731ed25-3f15-445a-9fe7-a3f586e7ab42.png)

![image](https://user-images.githubusercontent.com/107511412/174085046-676ebb60-c47c-4b71-8fc6-ab238e887629.png)

Lastly, I believe it is being interpreted as a variable in the mvt class... thoughts? Thanks!

**Comment by tobinbradley** [comment]
I don't have a 2.x PostGIS server lying around, but I did try adding a column named `q` to a table and was able to return a MVT correctly (Postgres 14/PostGIS 3.2). 

You could try logging the SQL call being generated and execute it on Postgres and see what it says. You can get a more detailed error message that way. Paste in a console.log to write the SQL to your terminal. If the SQL looks good but it spits back an error it's probably a PostGIS bug that got fixed. If there's a problem with the SQL then I should be able to fix it in `mvt.js`.

```javascript mvt.js
handler: function(request, reply) {
  console.log(sql(request.params, request.query))
  ...
```

If you are doing a lot of MVT output from PostGIS I highly recommend the 3.x upgrade. They made a lot of performance improvements.

**Comment by joseperez-GIS** [comment]
Ok. So, I did some testing and it does seem like the q is being understood as a variable, therefore the code is breaking:

First, I test the code on my DB:
![image](https://user-images.githubusercontent.com/107511412/175046263-16fe0a05-58ef-48b0-9863-eab49dc883a8.png)

Here, I change the the variable name of q to something else (say tobinbradley), and it works:

![image](https://user-images.githubusercontent.com/107511412/175047128-21707b0b-d888-4853-b751-c931d292c226.png)

Finally, I surround the q column with single quotes and it works too:
![image](https://user-images.githubusercontent.com/107511412/175048442-6fb7b06e-2617-48cc-b2dd-f556d9e64e91.png)

Thoughts? Would you like to try to come up with a fix or would you like me to take a stab at it?

**Comment by tobinbradley** [comment]
I think you've figured it out. In the postgis2x branch it names the subquery `q` and you also have a column named `q`, so my best guess is the `q` being passed is ambiguous to the parser. Changing the subquery name to anything but one of your column names fixes the problem. I'm guessing a bit - my version of Node apparently won't run the postgis2x branch - but it seems logical.

There's not a perfect fix for that. You have to name the subquery something, and if you run across a column with that same name you hit the same problem. If you rename it `qsubquery` and also are returning a column named `qsubquery` I think you hit the same thing. I'd just rename your subquery in your `mvt.js` file from `q` to something you're very unlikely to ever use as a column name like you did in the `tobinbradley` instance. 

The SQL call in the master branch is a lot cleaner and doesn't run in to this problem, but I don't think it can be adapted to PostGIS 2.x.

**Comment by joseperez-GIS** [comment]
I decided to just update to a most recent version of PostGIS since it has to be done either way at some point...

I see. Thank you for being so responsive!

**Comment by tobinbradley** [comment]
No worries! I think you'll be a lot happier with MVT creation in Postgis 3. There were a *lot* of performance enhancements.
