### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by CramericaIndustries** [tobinbradley/dirt-simple-postgis-http-api#56]
Found a possible bug in this [file](https://github.com/tobinbradley/dirt-simple-postgis-http-api/blob/3148be86a589e342a36e65398377c102c97973e6/routes/mvt.js#L14)

`...
      FROM
        ${params.table},
        (SELECT ST_SRID(${query.geom_column}) AS srid FROM ${
    params.table
...`

The SRID sub-query result might be null if there are rows in `params.table` where `query.geom_column` is null. And if that happens the outer query will always return no results, even if there are any.

Better do something like 
`...
      FROM
        ${params.table},
        (SELECT ST_SRID(${query.geom_column}) AS srid FROM ${
    params.table} WHERE ${query.geom_column} IS NOT NULL
...`

**Comment by tobinbradley** [comment]
Thanks for reporting this! It should be good now with v4.3.2. The same potential issue was present in all of the vector outputs - mvt, geojson, and geobuf.
