### ISSUE TITLE
My password contains the @ symbol in the db connection information. How do I handle it

### ISSUE THREAD

**Issue by geekljr** [tobinbradley/dirt-simple-postgis-http-api#60]
My password contains the @ symbol in the db connection information. How do I handle it。
like    "db": "postgres://name:WfdWc@d542dsd@ip:port/gis"

**Comment by tobinbradley** [comment]
Postgres supports what they call [percent encoding](https://www.postgresql.org/docs/current/libpq-connect.html), which looks like plain old ASCII encoding to me. I think the encoding for `@` is `%40`, so try `postgres://name:WfdWc%40d542dsd@ip:port/gis`.

If that doesn't work, it's up to you but if it were me I think I'd `ALTER USER x WITH PASSWORD 'noweirdcharacters';` before I put on a headlamp and went on a deep dive into the pg driver.
