### ISSUE TITLE
Serving through https

### ISSUE THREAD

**Issue by mtravis** [tobinbradley/dirt-simple-postgis-http-api#7]
We've added SSL to our server and as a consequence the api is bust. Is there something I need to to add to index.js to allow for this? 

https://maps.dartmoor.gov.uk/api/documentation

**Comment by tobinbradley** [comment]
Looks like your API is working fine - [https://maps.dartmoor.gov.uk/api/list_layers/v1](https://maps.dartmoor.gov.uk/api/list_layers/v1) - it's the doc page that's having trouble. It's looking for the service docs at http:// instead of https://.

I haven't tried setting it up behind a HTTPS proxy, but it looks like Hapi-Swagger has a [schemes](https://github.com/glennjones/hapi-swagger/blob/master/optionsreference.md) option you can set. I'd try changing index.js like this and see if it works.

```javascript
{
            register: HapiSwagger,
            options: {
                basePath: config.basePath,
                jsonPath: config.jsonPath,
                'schemes': ['https'],
                info: {
                    title: 'Dirt-Simple PostGIS REST API',
                    description: 'Created by Mecklenburg County GIS',
                    license: {
                        name: 'MIT Licensed - Fork me on Github!',
                        url: 'https://github.com/tobinbradley/dirt-simple-postgis-http-api'
                    }
                }
            }
```

**Comment by tobinbradley** [comment]
Don't forget to restart the service after changes :).

**Comment by mtravis** [comment]
Adding  'schemes': ['https'] didn't work. As the service is OK I'm happy
for now but will investigate this further next week.

**Comment by mtravis** [comment]
Still can't get this working. Tried combination of http & https on their own and together.

**Comment by tobinbradley** [comment]
Best guess is it's some configuration setting for hapi-swagger. If you've tried setting the host and schemes from the [config options](https://github.com/glennjones/hapi-swagger/blob/master/optionsreference.md) and that didn't work, I don't have any ideas. You could try updating to the latest hapi-swagger release and see if anything kicks loose.

I do hope you figure this out - we're going to https one of these days.

**Comment by mtravis** [comment]
Hey Tobin 

Did you ever go https and figure this one out?

**Comment by tobinbradley** [comment]
Nope. Seems like it's two issues with hapi-swagger (changing the docs asset path and changing the services location the docs are using) which should, in theory, be fixable via some combination of `swaggerUIPath` and `schemes` and `host` [options](https://github.com/glennjones/hapi-swagger/blob/master/optionsreference.md), but I don't have my hands on a convenient server to faff about with.

I should get a new HTTPS server soon, though I'm using *soon* in the IT sense of the word. When that happens I was planning on updating the library dependencies and updating the MVT creation for  PostGIS 2.4 and will have to tackle this problem out of necessity. 

Serving [HTTPS from node directly](https://stackoverflow.com/questions/5998694/how-to-create-an-https-server-in-node-js#14272874) should render the whole issue moot, but I prefer to handle that kind of stuff on the HTTP server end myself.

**Comment by tobinbradley** [comment]
I finally got around to setting up a test server and figuring this out. You need to do two things.

First, set up your API as an A name on your domain. I'm using api.myserver.gov as an example. Use an nginx or apache proxy to point that at your node server.

Second, set the swagger UI host and schemes options:

```javascript
server.register([
  Inert,
  Vision,
  {
    register: HapiSwagger,
    options: {
      basePath: '/',
      jsonPath: '/swagger.json',
      host: 'api.myserver.gov',
      'schemes': ['https'],
      info: {
        ...
      }
    }
  }
]);
```

That's it - you're good to go. The documentation comes up fine, and the service calls are correct and use HTTPS. I think you have to use an A name, not a relative path. My experiments with that went nowhere.

Hope that helps!

**Comment by mtravis** [comment]
Thanks for looking into this.

Might seem like a dumb question but how do I add an A name to my domain. I'm using apache on ubuntu 14.04. 

I've already have a proxy pointing at my node server. Can i just use that instead?

**Comment by tobinbradley** [comment]
You add an A name to your domain via your domain registrar (Go Daddy etc.). Your provider will have a control panel you can use on their web site someplace.

There doesn't seem to be a way to proxy from a subfolder and have the documentation work - there's an [open issue about it](https://github.com/glennjones/hapi-swagger/issues/363). I think the hapi-swagger devs expect people to use A names.

**Comment by mtravis** [comment]
Ah ok. I'll speak to the web guys at work about setting up the A name. I'm
not sure if they'll go for it so I might just run it from my own digital
ocean server.

Thanks for your help.

**Comment by tobinbradley** [comment]
No worries!

**Comment by smnorris** [comment]
I feel so close to having this work but am not quite there - I think https might be the issue.

I have dirt installed and running, and I can query my custom route on my server successfully with this:
```
curl -X GET "http://127.0.0.1:3000/v1/nearest_stream/-123.704567%2C48.772027%2C4326?limit=1" -H "accept: application/json"
[{"rowjsonb_to_geojson":"{\"type\": \"Feature\", \"geometry\": {\"type\": \"Point\", \"coordinates\": [-123.704553540741, 48.7720147199211]}, \"properties\": {\"gnis_name\": \"Cowichan River\", \"wscode_ltree\": \"920.252823\", \"blue_line_key\": 354155148, \"localcode_ltree\": \"920.252823.065223\", \"linear_feature_id\": 710282032, \"distance_to_stream\": 1.69}}"}]
```
but get no joy via https
```
curl -X GET "https://www.hillcrestgeo.ca/fwa/v1/nearest_stream/-123.704567%2C48.772027%2C4326?limit=1" -H "accept: application/json"
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```
The documentation isn't found either: [https://www.hillcrestgeo.ca/fwa/](https://www.hillcrestgeo.ca/fwa/)

Do I need to set up the A name even though I'm running through an nginx proxy, like you've noted in the bottom of `config/README.md`?

Thanks for this great project, setting up the API was a breeze... but now that I'm on the final sysadmin steps I'm stumped.

**Comment by tobinbradley** [comment]
Two things to try here.

nginx does different things when you do or do not have a trailing slash on your proxy. I think in this case you'd need a trailing slash, unlike the DO example, otherwise it'll pass the "/fwa/" part to node, and your node app doesn't have a route that corresponds to that (hence 404). So something like:

```nginx
location /fwa/ {
   proxy_pass http://localhost:8081/;
}
```

Instead of:

```nginx
location /fwa {
   proxy_pass http://localhost:8081;
}
```

You'll also need to set the swagger.basepath in the config to "/fwa". 

An A name solves all of those problems and gives you a cool URL like 'fwa.hillcrestgeo.ca', but it should work the other way too, and it might be easier than trying to get your IT department to do the 2 minutes of work it would take to add an A name (I've been there ;).

**Comment by smnorris** [comment]
Awesome. A trailing slash in the location block was all that was needed! I had already (eventually) noticed the swagger.basepath needed to be changed. 

As I'm the IT department, the A name addition is easy enough to go ahead with. But since I'm the IT department, I wasn't quite ready to start messing with that without quite understanding what is going on and bringing the whole house of cards crashing down.

Thanks for your help, much appreciated.

**Comment by smnorris** [comment]
For any interested, this is what I had, that got the 404 - only one critical trailing slash:
```
        location /fwa {
          proxy_pass http://localhost:3000/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
```

fixed:

```
        location /fwa/ {
          proxy_pass http://localhost:3000/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
```
