### ISSUE TITLE
postgis geometry table

### ISSUE THREAD

**Issue by abenrob** [tobinbradley/dirt-simple-postgis-http-api#9]
Hey - Nice project! I was playing around with it, and had an error with [this line](https://github.com/tobinbradley/dirt-simple-postgis-http-api/blob/master/routes/mvt_v1.js#L29). PostGIS' `find_srid` function looks in the GEOMETRY_COLUMNS table to identify the SRID. If the geometry column was not added with `AddGeometryColumns()` it will not be present in the table, and will return `0` for the SRID.
Not so much a bug as a heads-up. In my case, I rewrote that line to 
```
sql.where(`
${request.query.geom_column} && 
ST_Transform(ST_MakeEnvelope(${smBounds.join(',')} , 4326),
(SELECT ST_SRID(${request.query.geom_column}) FROM ${request.params.table} LIMIT 1))
`);
```

**Comment by tobinbradley** [comment]
Would you by chance be using an older version of PostGIS (<2)? At PostGIS 2 the geometry_columns table became a geometry_columns view and is no longer updated by AddGeometryColumns (see [first note](http://postgis.net/docs/AddGeometryColumn.html) in docs). It reads from system catalogs any table or view with a geometry type. 

This is still a good catch. I need to at the very least as a note to the readme about PostGIS versions. Thanks!

**Comment by abenrob** [comment]
postgresql 9.5.5, postgis 2.3.1.
GEOMETRY_COLUMNS view shows srid = 0 for all tables, but st_srid returns the appropriate srid. I'll have to ask the creator how on earth the geometry field was defined without defining the srid...

**Comment by tobinbradley** [comment]
Probably loaded the data without specifying a SRID, so the geometry column itself doesn't have a SRID constraint, but each geometry column record will have a SRID associated with that piece of geometry. Probably not best practice, as you could have a 10 record table with each record in an entirely different projection, which isn't ideal. But as long as every table record maintains the same projection it should be OK.
